repos:
  # ------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=4096"]
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^tests/

  # ------------------------------------------------------------------
  - repo: https://github.com/asottile/setup-cfg-fmt
    # Этот хук автоматически форматирует файл setup.cfg,
    # чтобы он соответствовал определенным стандартам и стилю.
    # Это может включать выравнивание, удаление лишних пробелов,
    # упорядочивание секций и параметров, а также приведение
    # к единому стилю.
    # Полезен в сочетании с другими инструментами, такими как
    # black или isort, для обеспечения согласованности стиля
    #кода и конфигурации в проекте.
    rev: v2.7.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/asottile/reorder-python-imports
    # Этот хук предназначен для автоматической реорганизации
    # импортов в Python-коде.
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
        args: [
            --application-directories=.:src,
            #--py312-plus,
            --add-import,
            "from __future__ import annotations",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: tests/
        args: [
            --line-length=88,
            --target-version=py311,
            #--check
          ]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-logging
          - flake8-tidy-imports
        exclude: ^tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        #language_version: python3.12
        exclude: ^(docs/|exampls/)
