Проанализируй этот файл pre-commit-config.yaml и подбери подходящие хуки.
repos:

- repo: https://github.com/pre-commit/mirrors-isort
  # Форматирует импорты в соответствии с заданным профилем
  rev: v5.6.4
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/psf/black
  # Форматирует код в соответствии с профилем black
  rev: 20.8b1
  hooks:
    - id: black

- repo: https://github.com/PyCQA/pylint
  # Проверяет код на соответствие стандартам
  rev: v2.9.6
  hooks:
    - id: pylint

- repo: https://github.com/psf/blacken-docs
  # Форматирует документацию в формате Markdown
  rev: v1.9.0
  hooks:
    - id: blacken-docs

- repo: https://github.com/PyCQA/bandit
  #
  rev: v1.7.0
  hooks:
    - id: bandit

- repo: https://github.com/pre-commit/pre-commit-hooks
  # Проверяет код на соответствие стандартам
  rev: v2.3.0
  hooks:
    - id: flake8
      args: ["--ignore", "E501,W503"]
    - id: check-json
    - id: check-yaml
    - id: name-tests-test
      args: ['--django']
    - id: debug-statements
    - id: end-of-file-fixer
      types: [python]
#    - id: no-commit-to-branch
#      args: ["--branch", "master", "--branch", "main"]
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: requirements-txt-fixer
    - id: check-added-large-files

- repo: https://github.com/pre-commit/mirrors-mypy
  # Проверяет типы в коде. 
  rev: v0.790
  hooks:
    - id: mypy

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
    - id: nbqa-isort
    - id: nbqa-black
    - id: nbqa-flake8
      args: ["--ignore=E501,E402"]
    - id: nbqa-mypy
      args: ["--ignore-missing-imports"]
    - id: nbqa-pylint
      args: ["--disable=E0401,C0413,C0114,C0301"]

#- repo: local
#  hooks:
#    - id: unittest
#      name: unittest
#      entry: python -m unittest discover
#      language: python
#      always_run: true
#      pass_filenames: false
